---
# - hosts: all
#   # connection: local
#   tasks:
#     - debug: var=ansible_all_ipv4_addresses[1]
#     - debug: var=ansible_default_ipv4.address

- hosts: all
  become: yes
  gather_facts: yes
  # debugger: on_failure
  strategy: free
  roles:
    - roles/common
    - roles/java

- hosts: elasticsearch
  become: yes
  gather_facts: yes
  strategy: free
  roles:
    - roles/elasticsearch

- hosts: kibana
  become: yes
  gather_facts: yes
  # strategy: free
  tags:
    - kibana
  roles:
    - roles/kibana

- hosts: logstash
  become: yes
  gather_facts: yes
  # strategy: free
  roles:
    - roles/logstash

